# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3baac05306359d69c7abe988fbebe73661aa44e368620f7d6009c262ca5fc921e48a8c09553f9bbadcf93ab33fc1980e29bffe3fb7ee7357760a8c5820d1a0fb

test:
  secret_key_base: bb21cd183e0963205e40e4fded72aba55d32c185b5a2a6dd407f044caa80b2245adfb2778102d736fdb89c6c76cd01d7038f102b22936a5c04d54a759a000d70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
